### ISSUE TITLE
is the embed/iframe code available?

### ISSUE THREAD

**Issue by wokawoka** [langolierz/auth-rocketchat-from-discourse#6]
sorry for asking it here but is there by chance the possibility to take a look at the embedding code of the rocket chat  iframe? I tried it on scanlines and it looks and works great. I would like to implement it in the same way, if possible.
Thank you!

**Comment by cyberboy666** [comment]
hey @wokawoka - no worries - thanks for checking it out !

that iframe code was written by @doubleobelisk - ican ask them if they want to share it and how

**Comment by wokawoka** [comment]
thank you for replying @langolierz !

it would be really great to see that code. I really like a lot that iframe scrolling from below.
Thank you again for having shared your project

**Comment by palomakop** [comment]
sure, here's what we are using currently, of course you would want to change the iframe src url and chat header text/link

this part goes in the `css` section:
```
.collapsible {
    height: 570px;
    width: 500px;
    float: right;
    position:fixed;
    bottom: -540px;
    right: 0;
    z-index:10000;
}

.active_chat {
    position:fixed;
    bottom:0;
}

.chat_header {
    height: 20px;
    width: 478px;
    position:relative;
    padding: 5px 10px;
    background-color:white;
    border: 1px solid black;
    text-align:left;
    color:black;
}

.chat_header a {
    color:black;
}

.chatbutton.active {
    -webkit-box-shadow: none;
	-moz-box-shadow: none;
	box-shadow: none;
}

.chatbutton {
    outline:none;
    float:right;
    position: absolute;
    right: 5px;
    border:none;
    background: none;
}

.chat_container {
    width: 498px;
    height: 537px;
    border: 1px solid black;
    border-top: none;
    background:#2f343d;
}


.chat_embed {
    width: 100%;
    height: 100%;
    border-style:none;
}
```

this part goes in the `</body>` section:
```
<div class="collapsible">

<div class="chat_header">
<a href="https://chat.scanlines.xyz" target="_blank">chat.scanlines.xyz</a>
<button type="button" class="chatbutton">show</button>
</div>

<div class="chat_container">
</div>

</div>

<script>
var coll = document.getElementsByClassName("chatbutton");
var i;
var content_toggle = true;
document.getElementsByClassName("chat_container").innerHTML='';

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
      var x = this.parentElement.parentElement.classList.toggle("active_chat");
      var content = this.parentElement.nextElementSibling;
      content_toggle = !content_toggle
    if (content_toggle == false) {
        this.innerHTML = 'hide'
        content.innerHTML = '<iframe src="https://chat.scanlines.xyz/channel/general" class="chat_embed"></iframe>';
    } else {
        this.innerHTML = 'show'
        content.removeChild(content.firstChild);
    }
  });
}
</script>
```

**Comment by palomakop** [comment]
by the way, this is contained in a custom theme component, if that wasn't evident.

**Comment by cyberboy666** [comment]
i can also add this info to the [scanlines-technical-details](https://github.com/langolierz/scanlines-technical-details) repo

**Comment by cyberboy666** [comment]
https://github.com/langolierz/scanlines-technical-details/blob/master/embedded_chat_window_for_discourse.md

**Comment by wokawoka** [comment]
hey @doubleobelisk , sorry for replying late! I missed the notification of your reply (too many emails from github).
Thank you so much for taking the time to the whole code. It will be extremely useful. 
I'll surely try it out as soon as possibile. I will also have to try to integrate to nextcloud (which is already integrated with our instance of discourse) so I'll also try to figure out if there's a way to adapt for it as well. In every case I will report back.
Thank you very much again for the superuseful information!
